# Generated by Django 4.0.6 on 2022-07-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('doc_name', models.CharField(blank=True, default='', max_length=200)),
                ('sector', models.CharField(blank=True, default='Physiothrapist', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('doc_notice', models.TextField()),
            ],
            options={
                'ordering': ['joined'],
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=200)),
                ('patient_typ', models.CharField(blank=True, default='', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
    ]
